version: "3"

services:
  python:
    build: ./
    volumes:
      - ./data:/app/data
    container_name: python_container

  node:
    build: ./nodejs
    volumes:
      - ./data:/app/data
    ports:
      - "8090:8090"
    depends_on:
      - python
    container_name: node_container
